### ISSUE TITLE
Value error 

### ISSUE THREAD

**Issue by vijpandaturtle** [smatt989/ActiveLearning#2]
Tried running the python script in a jupyter notebook.
I keep getting this error.
ValueError                                Traceback (most recent call last)
<ipython-input-5-bba558a68a4e> in <module>()
    241 # turned on, classifying digits from 0-9, with re-sampling and printing test results every 5 mini-batches
    242 # in addition it would then run 20 epochs at intervals of 250 label counts
--> 243 make_a_good_test(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), sys.argv[4] == 'True', extra_sampling, print_every)

ValueError: invalid literal for int() with base 10: '-f'
I'm unable to find the source of this error ..would you be able to help me backtrack ? 
Thanks

**Comment by smatt989** [comment]
Hi can you please copy and paste how you are calling the script?  it appears that you are using "-f" where a numerical parameter is required.  thanks!

**Comment by vijpandaturtle** [comment]
I simply run the cell containing the code in a jupyter notebook

**Comment by smatt989** [comment]
I think I see the problem.  

The last line should be commented out.  

Simple remove it, and then call make_a_good_test with your own parameters.  for example:
make_a_good_test(1, 50, 40, True, False, 100)

**Comment by vijpandaturtle** [comment]
Aaah I didn't realize that you used command line arguments. Thanks a lot !

**Comment by smatt989** [comment]
Haha yes -- I would often call this script from the command line and pass in arguments there, so that's not going to work if you aren't doing that :)

Let me know if you run into any further issues!
